server:
  port: 9001
spring:
  application:
    name: nacos-pay-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719 # 默认端口8719
