server:
  port: 9528

spring:
  application:
    name: cloud-alibaba-sentinel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: pay_routh1
          uri: lb://nacos-pay-provider
          #          uri: http://localhost:9001
          predicates:
            - Path=/pay/**